### ISSUE TITLE
Impossible de lancer Finalynx

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#102]
Quand je lance le dashboard avec -f avant il me demandait de m'identifier ou le code mais là plus rien

[00:09:45] No cache file found, fetching data.

et si j'appuie sur entrée

[00:09:55] Found saved credentials, logging in.                                                     source_finary.py:103
           No credentials file, environment variables, or cookies file. Skipping fetching.          source_finary.py:143
           Error: Couldn't fetch data, please try using the `-f` option to signin again.               source_base.py:70
           Details: Finary signin failed.                                                              source_base.py:73
           Saved current portfolio to 'logs/finalynx_2023-05-26.json'                                   assistant.py:280

**Comment by MadeInPierre** [comment]
Bizarre, tu as changé de version ? Quelle version maintenant ? 

Il y a quelques jours l'API était morte mais je viens d'essayer et ça marche chez moi

**Comment by sebfar9172** [comment]
La 1.16.1

J'ai désinstallé et réinstallé mais sans résultat

**Comment by MadeInPierre** [comment]
La petite animation de chargement cachait une ligne qui demande une info à l'utilisateur, d'où le blocage. 

Par contre je n'ai pas de problème de signin, peut-être t'es-tu trompé de émail/mdp ?

**Comment by sebfar9172** [comment]
avec la version que tu viens de publier j'ai bien le user/mdp qui est demandé (ce qui n'était pas le cas pour moi dans la version précédente). Par contre il ne me demande pas le code 2FA et m'affiche

Details: Expecting value: line 1 column 1 (char 0)

**Comment by sebfar9172** [comment]
je n'ai rien dit c'est bon
