### ISSUE TITLE
impossible d'affecter une enveloppe à mes startups

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#103]
Bonjour

j'ai la donnée suivante : 
│ SF5591                                                                                                               │
│ ├── 53 € Nothing id='10506'                                                                                          │

si je met cela dans un dossier, cela fonctionne 
                            Line("Nothing", key="10506"),

mais si je défini l'enveloppe suivante (avec key ou sans) cela m'affiche 0 et je ne comprend pas pourquoi
    startupNothing=Envelope("Nothing ","STP", date_created=date(2022, 4, 6), date_unlock=date(2027, 4, 6))                                     
et dans le dossier 
                            Line("Nothing", envelope="startupNothing", key="10506"),

**Comment by MadeInPierre** [comment]
Hello, je vois qu'il y a des guillements en trop dans cette ligne : 

```python
Line("Nothing", envelope="startupNothing", key="10506"),
```

qui devrait être : 
```python
Line("Nothing", envelope=startupNothing, key="10506"),
```

car `envelope` a besoin de l'objet Python entier, j'espère que ça suffit à corriger :crossed_fingers:

**Comment by sebfar9172** [comment]
Non je n'ai pas mis de guillemets et c'est la même chose

**Comment by MadeInPierre** [comment]
`SF5591` est le nom de ton compte qui contient Nothing dans Finary ? 

Déjà je remarque un espace en trop à `"Nothing "` dans : 

```python
Envelope("Nothing ","STP", date_created=date(2022, 4, 6), date_unlock=date(2027, 4, 6))
```

Ca suffit peut-être à résoudre le souci. Sinon, peux-tu essayer avec : 

```python
Envelope("Nothing", "STP", date_created=date(2022, 4, 6), date_unlock=date(2027, 4, 6), key="SF5591")
```

**Comment by sebfar9172** [comment]
oui c'est bon avec la dernière proposition
