### ISSUE TITLE
Page web : avoir l'arborescence fermée

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#104]
Bonjour
Serait il possible que sur la page web que tout soit fermé par défaut et quand j'ouvre un dossier ses sous dossiers soient fermés ... En effet, avec tout le détail ce n'est pas très lisible

**Comment by MadeInPierre** [comment]
Hello, assez facile à faire je crois mais ça ne risque pas d'être fatiguant de rouvrir l'arbre à chaque fois que tu ouvres la page ? 

Si ça te suffit tout va bien, après on pourrait sauvegarder des préférences et tout mais ça prend tout de suite plus de temps à implémenter

**Comment by sebfar9172** [comment]
En effet cela pourrait être lourd 
Le plus simple c'est peut être d'avoir la possibilité de fermer tous les sous dossiers d'un coup au lieu d'avoir à le faire sous dossier après sous dossier

**Comment by sebfar9172** [comment]
Au final j'ai utilisé l'option Display avec Collapsed que je ne connaissais pas et qui me permet de ne pas avoir le détail pour les comptes où je ne touche pas à la composition comme mon PEE et dans le cas du crowdlending dont les centaines de lignes de projet ne me servent à rien
