### ISSUE TITLE
décalage delta

### ISSUE THREAD

**Issue by yovanoc** [MadeInPierre/finalynx#105]
J'utilise iTerm2 au cas ou et je sais pas si je suis le seul à avoir ça mais j'ai un décalage sur les delta (il se met une ligne au dessus):

<img width="714" alt="image" src="https://github.com/MadeInPierre/finalynx/assets/7302317/b0600ba5-1421-4521-a14f-c89fbc4729ff">

**Comment by MadeInPierre** [comment]
Hello ! Mince, j'avais ce souci quand j'utilisais des `newline=True` pour espacer les lignes, tu en utilises aussi ? 

C'était censé être résolu mais bon, pas sur toutes les configs ^^ Sans contexte supplémentaire je peux juste te pointer vers le [code qui s'occupe de ça](https://github.com/MadeInPierre/finalynx/blob/8c5a78fc8df7e781783c1877b29b25589fe14bc3/finalynx/portfolio/folder.py#L177-L196), difficile de trouver le souci exact sans la config voire peut-être données.

**Comment by MadeInPierre** [comment]
P.S. Promis un moyen de changer les couleurs arrive : 
- #77

**Comment by yovanoc** [comment]
Avec ou sans les newline ça change rien

**Comment by MadeInPierre** [comment]
Le [partage de](https://github.com/MadeInPierre/finalynx/discussions/75#discussioncomment-6016829) @nmathey m'a aidé à trouver la cause, je suis le seul à utiliser `hide_root=True` et je n'ai pas ce problème (vous l'avez tous les deux), solved :crossed_fingers:
