### ISSUE TITLE
Pas le nom des actions dans mon PEA dans la console

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#113]
Dans mon PEA ou dans ma Ledger je n'ai pas le détail, il semble que cela soit pour tous ceux qui ont 3 niveaux de profondeur

![image](https://github.com/MadeInPierre/finalynx/assets/52531214/0be16aea-e510-4bd2-a145-0985cdb41621)

**Comment by sebfar9172** [comment]
résolu avec les thèmes 👍

**Comment by MadeInPierre** [comment]
Ah super ! Parfait pour partager si t'as toujours envie :innocent: : 
- #75
