### ISSUE TITLE
Source Realt : erreur lors du fetch

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#118]
Hello

J'ai l'erreur suivante 

[11:52:43]     Error: Couldn't fetch data, please try using the `-f` option to signin again.                                                                                                     source_base.py:174
               Details: 'realtoken-25097-andover-drive-dearborn-mi'

Mais le -f ne change rien

**Comment by sebfar9172** [comment]
Cela vient du fait que dans la liste issu de Realt : Drive est traduit en DR

REALTOKEN-25097-ANDOVER-DR-DEARBORN-MI

**Comment by MadeInPierre** [comment]
@nmathey Bienvenue dans ton nouveau rôle de tech support : c'est toi le pro pour celle-ci :smile:

**Comment by sebfar9172** [comment]
et ce n'est pas systématique :(

**Comment by nmathey** [comment]
Arf ok pour faciliter la récupération des infos des token en collatéral sur RMM je me base sur le nom du token seulement: effectivement si le nom diffère ca ne va pas le faire. Je vais essayer de trouver le moyen de récupérer directement l'adresse du contrat.

**Comment by MadeInPierre** [comment]
Mince, si ça devient trop compliqué on devra le laisser comme ça et marquer la limitation... si t'y arrives tant mieux, mais bon on fait ce qu'on peut :)

**Comment by nmathey** [comment]
Oui je vais trouver le moyen maintenant je ne sais pas quand ^^ communiquons sur cette limitation et je garde l'issue à ma charge

**Comment by MadeInPierre** [comment]
Merci pour ton temps ! Je mets une petite note dans la [release](https://github.com/MadeInPierre/finalynx/releases/tag/v1.18.0) et garde cette issue ouverte pour suivre

**Comment by MadeInPierre** [comment]
Proposition bête et très moche mais assez simple : matcher le nom le plus proche de la liste RMM plutôt que des noms exacts, voir par exemple https://stackoverflow.com/questions/10018679/python-find-closest-string-from-a-list-to-another-string 

Je ne connais pas RealT ni RMM etc, il y a peut-être un meilleur moyen, mais voilà proposition dans le vide

**Comment by nmathey** [comment]
@sebfar9172 tu me confirmes (en regardant le cache de realT peut être) que le uuid de ce token est bien 0xF18CfFB528eca0ea31D1d6b28BC80d2eca34D14D?

Ce token n'est pas "collatérable" donc le soucis ne vient pas du RMM. Par contre il s'agit d'un des premiers token initialement sur Ethereum et ensuite basculés sur Gnosis.

La réponse de l'API me renvoie les deux infos mais jamais avec le "DRIVE" en entier...:
```
{
    "fullName": "OLD-25097 Andover Dr, Dearborn Heights, MI 48125",
    "shortName": "OLD-25097 Andover",
    "symbol": "REALTOKEN-25097-ANDOVER-DR-DEARBORN-MI",
    "tokenPrice": 60.68,
    "currency": "USD",
    "uuid": "0x74d2cb65B1158300c3e6BeA149d68509C7B2425d",
    "ethereumContract": "0x74d2cb65B1158300c3e6BeA149d68509C7B2425d",
    "xDaiContract": null,
    "gnosisContract": null,
    "lastUpdate": {
      "date": "2023-05-25 17:01:35.000000",
      "timezone_type": 3,
      "timezone": "UTC"
    }
```

et

```
{
    "fullName": "25097 Andover Dr, Dearborn Heights, MI 48125",
    "shortName": "25097 Andover",
    "symbol": "REALTOKEN-25097-ANDOVER-DR-DEARBORN-MI",
    "tokenPrice": 60.68,
    "currency": "USD",
    "uuid": "0xF18CfFB528eca0ea31D1d6b28BC80d2eca34D14D",
    "ethereumContract": "0xF18CfFB528eca0ea31D1d6b28BC80d2eca34D14D",
    "xDaiContract": "0xF18CfFB528eca0ea31D1d6b28BC80d2eca34D14D",
    "gnosisContract": "0xF18CfFB528eca0ea31D1d6b28BC80d2eca34D14D",
    "lastUpdate": {
      "date": "2023-05-25 17:01:38.000000",
      "timezone_type": 3,
      "timezone": "UTC"
    }
```

L'erreur ne semble pas venir de la réponse API.

Tu peux checker directement ton portefeuille sur blockscout (ou me partager ton addresse public) afin voir sous quelle forme se token apparait?
`https://blockscout.com/xdai/mainnet/address/<ton address de portefeuille realT ici>/tokens#address-tabs`

**Comment by nmathey** [comment]
Re,

Bizarre j'ai trouvé le token sous blockscout qui effectivement renvoit en symbol avec DRIVE alors que l'API RealT ale symbole avec DR seulement.

`"contractAddress":"0xf18cffb528eca0ea31d1d6b28bc80d2eca34d14d","decimals":"18","name":"RealToken S 25097 Andover Dr Dearborn MI","symbol":"REALTOKEN-25097-ANDOVER-DRIVE-DEARBORN-MI","type":"ERC-20"`

Je vais demander à la communiste qui maintient l'API savoir si ce problème est déjà arrivé.
Je regarde aussi du côté de ton idée Pierre https://github.com/MadeInPierre/finalynx/issues/118#issuecomment-1570034817

**Comment by MadeInPierre** [comment]
Ca y est vous me parlez en chinois (et en plus je le parle un peu) ^^ bon courage ! 🫡

**Comment by sebfar9172** [comment]
@nmathey je te confirme que je n'ai rien en RMM pour ma part

**Comment by MadeInPierre** [comment]
Super ! Juste fais gaffe, je viens de push un fix pour #117, mieux vaut pull avant de commit/push par sécurité ^^

**Comment by sebfar9172** [comment]
J'ai essayé mais cela ne fonctionne pas
Je vais attendre la prochaine version

**Comment by sebfar9172** [comment]
avec la dernière version des sources c'est bon :)
