### ISSUE TITLE
Hide deltas in the recommendations panel when they're OK

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#121]
J'ai un dossier PEA Fortuneo qui n'apparait pas dans la section Delta Investments

Quelle est la règle pour qu'il apparaisse ?

**Comment by sebfar9172** [comment]
et dernière info, à chaque fois que je lance Finalynx, le delta ne contient pas les mêmes dossiers

**Comment by MadeInPierre** [comment]
Pourrais-tu essayer d'utiliser cette structure dans `ta_config.py` : 

```python
envelope1 = Envelope(...)
envelope2 = Envelope(...)
envelope3 = Envelope(...)

envelopes = [
    envelope1,
    envelope2,
    envelope3
]

bucket1 = Bucket(...)
bucket2 = Bucket(...)

buckets = [
    bucket1,
    bucket2
]


portfolio = ...

assistant = Assistant(portfolio, buckets, envelopes, ...)
assistant.run()
```

Le genre de trucs qu'il faudrait que j'ajoute dans la doc ^^" Et c'est pas très propre pour l'instant, structure à améliorer...

**Comment by sebfar9172** [comment]
J'ai fait cela mais toujours le même soucis : Epargne de précaution min. ne s'affiche pas

             Folder(
                "Epargne de précaution",
                target=TargetMin(10000),
                children=[
                    SharedFolder(
                        "Epargne de précaution min.",
                        bucket=bucket_garanti,
                        target=TargetMin(7500),
                        display=FolderDisplay.COLLAPSED,
                        target_amount=7500,
                    ),
                    SharedFolder(
                        "Epargne de précaution compl.",
                        bucket=bucket_garanti,
                        target=TargetMin(2500),
                        display=FolderDisplay.COLLAPSED,
                        target_amount=2500,
                    ),
                ],
            ),
             Folder(
                "Court terme",
                target=TargetMin(1000),
                children=[
                    SharedFolder(
                        "Divers",
                        bucket=bucket_garanti,
                        target=TargetMin(1000),
                        display=FolderDisplay.COLLAPSED,
                    ),
                ],
            ),

**Comment by MadeInPierre** [comment]
Hello, j'ai essayé de reproduire la même chose avec ton code et mon compte Finary, ce qui me donne : 

![image](https://github.com/MadeInPierre/finalynx/assets/12670280/60beb7a7-dd74-47c0-a279-19d7078be8a9)

Je ne vois pas d'erreur, Finalynx me dit d'investir là où il manque de l'argent. Pour info quand un target est respecté il ne s'affiche pas dans Delta Investments.

Ai-je mal compris le souci ? Ma config reproduite n'est pas ce que tu vois ? Je veux bien un screen de juste la partie court terme  si tu veux bien (rien de bien secret dans les montants j'imagine)

**Comment by sebfar9172** [comment]
C'est bizarre ce que tu me dis car dans la partie delta il y a des lignes avec des coches qui semblent vouloir dire qu'il n'y a pas de delta

**Comment by sebfar9172** [comment]
![ecran1](https://github.com/MadeInPierre/finalynx/assets/52531214/10882b58-b6cb-4d3f-a234-72cbb277cfc5)
![ecran2](https://github.com/MadeInPierre/finalynx/assets/52531214/e58f6f31-2b45-4e79-b98c-f0804643c42c)

**Comment by MadeInPierre** [comment]
Merci pour le screen ça aide ! 

Tiens j'ai le même souci en essayant de faire pareil : 

<img src="https://github.com/MadeInPierre/finalynx/assets/12670280/6e2d913e-3808-4d59-8999-e9718c54ab4a" width=600/>

**Comment by MadeInPierre** [comment]
Juste pour info, sur mon compte (sans bugs :upside_down_face:) ça ressemble à ça : 

<img src="https://github.com/MadeInPierre/finalynx/assets/12670280/26e0c705-c7bd-4f89-b56d-68a01d28b91a" width=400/>

**Comment by MadeInPierre** [comment]
Ok je m'en occupe quand je peux :slightly_smiling_face:

**Comment by sebfar9172** [comment]
Cela me paraît bien

**Comment by MadeInPierre** [comment]
Je push et on espère que c'est bon :crossed_fingers:

**Comment by MadeInPierre** [comment]
Bizarre, avec mon compte perso et ta config ça donne ceci : 

![image](https://github.com/MadeInPierre/finalynx/assets/12670280/194f6699-983f-4ef7-95c5-c22ba93359ca)

Je ne vois pas la cause d'ici, si tu veux que je teste avec tes données j'aurais besoin de ton fichier `finalynx/fetch/finary_cache.json` (tu peux enlever les lignes qui ne concernent pas cette issue) et me l'envoyer ici en pièce jointe, telegram @MadeInJack, ou sur linkedin sur mon profil github.

--- 

Pour les `[?]` un peu partout, ça devrait pouvoir se résoudre si tu installes une police de texte qui supporte l'UTF-8 (c'est l'encodage international pour caractères spéciaux que Windows ne supporte pas par défaut...) ou installer un nouveau terminal moderne pour Windows comme https://tabby.sh/ 

Tu as changé les couleurs avec un thème perso ? Bizarre que les deltas positifs soient en rouge déjà :sweat_smile: Si ça vient du terminal il faudrait que tu crées un thème perso avec des couleurs que ton terminal accepte (un peu d'essais-erreurs jusqu'à trouver malheureusement) ou essayer https://tabby.sh/ 

Dernier tip, vu que la majorité des lignes sont des actions, tu peux mutualiser tout ça dans le `Folder` PEA : 

```python
Folder(
    "PEA Fortuneo",
    target=TargetMin(16000),
    asset_class=AssetClass.STOCK,
    asset_subclass=AssetSubclass.STOCK_SHARE,
    envelope=pea_fortuneo,
    children=[
        Line("BNP Paribas", target=TargetRatio(10, 1), key="8666158"),
        Line("Carrefour", target=TargetRatio(10, 1), key="8666159"),
        Line("Korian", target=TargetRatio(10, 1), key="8666160"),
        Line("Orange", target=TargetRatio(10, 1), key="8666161"),
        Line("La Francaise des Jeux", key="8666163"),
        Line("TF1", target=TargetRatio(10, 1), key="8666162"),
        Line(
            "Amundi PEA S&P 500 UCITS ETF",
            asset_subclass=AssetSubclass.ETF,
            target=TargetRatio(10, 1),
            key="8666164",
        ),
        Line("Michelin (CGDE)", target=TargetRatio(10, 1), key="8666168"),
        Line(
            "Lyxor Euro Stoxx 50 (DR) UCITS ETF Acc",
            asset_subclass=AssetSubclass.ETF,
            target=TargetRatio(10, 1),
            key="8666165",
        ),
        Line(
            "Lyxor MSCI Emu Small Cap (DR) UCITS ETF Dist",
            asset_subclass=AssetSubclass.ETF,
            target=TargetRatio(10, 1),
            key="8666166",
        ),
        Line("SPIE SA", target=TargetRatio(10, 1), key="8666167"),
        Line("Liquidites", AssetClass.CASH, AssetSubclass.LIQUIDITY, key="8445408"),
    ],
),
```

**Comment by sebfar9172** [comment]
je t'ai envoyé le fichier sur telegram

ok je vais voir pour la police de caractères

Oui j'ai changé les couleurs :)

c'est noté pour l'astuce

**Comment by sebfar9172** [comment]
Comme indiqué par telegram pour mon PEA si j'utilise l'option COLLAPSED le delta global du PEA apparait mais si je l'enlève le delta de chaque ligne n'apparait pas ....

**Comment by MadeInPierre** [comment]
Après recherches, il ne faut pas oublier de suivre la [structure recommandée](https://github.com/MadeInPierre/finalynx/issues/121?notification_referrer_id=NT_kwDOAMFVSLM2NjIyNTc5ODU0OjEyNjcwMjgw#issuecomment-1570440657) pour obtenir les recommendations : 

```python
Assistant(portfolio, buckets, envelopes, ...)
```
