### ISSUE TITLE
Error after install finalynx

### ISSUE THREAD

**Issue by Sigri44** [MadeInPierre/finalynx#122]
Hello,

Have follow instructions, install pip finalynx, copy demo.py, and launch it : 

<img width="1206" alt="image" src="https://github.com/MadeInPierre/finalynx/assets/9304947/6f4c1f12-78b0-4a3a-834c-c935c30e5bfb">

Thank you

**Comment by Sigri44** [comment]
Hello !

Parfait faisons comme ça ;)

Voici les infos : 
<img width="193" alt="image" src="https://github.com/MadeInPierre/finalynx/assets/9304947/52388c81-705f-4f10-8ae3-d8df0784ccb9">

<img width="910" alt="image" src="https://github.com/MadeInPierre/finalynx/assets/9304947/5ddc7e59-6164-4d7c-83ca-e8f7ad00d50d">

Pas de python 2, uniquement du python3/pip3.

Habituellement je passe via des requirements.txt, cela change quelque chose ?

Have fun !

**Comment by MadeInPierre** [comment]
Bon je ne connais pas du tout homebrew, c'est un truc pour Mac je crois ? Si c'est un problème lié à ça je peux ne pas aider ni tester chez moi :sweat_smile: Il est visiblement en train de chercher des fichiers dedans...

Question bête désolé mais juste au cas où, tu as bien clone le repo et tu es bien dans le dossier racine de Finalynx avant d'appeler `pip3 install -e .` ? Je dis ça car poetry cherche un fichier `project.toml` qui est à la racine de Finalynx, normalement il devrait le trouver sans soucis si tu es au bon endroit.

Autre idée, peut-être que ton fichier `finalynx.py` (qui est ta config perso n'est-ce pas ?) perd un peu le système par conflits de nom, puisque le package entier s'appelle déjà `finalynx`. Pourrais-tu essayer de le renommer vers un truc genre `my_config.py` et le placer dans un dossier random loin des fichiers internes Homebrew (genre le dossier Documents ou autre) pour éviter tout conflit?

**Comment by MadeInPierre** [comment]
Pour résumer il y a 2 options qui devraient marcher : 

1. Installer via pip, et copier le fichier exemple `demo.py` quelque part dans tes dossiers perso (e.g. Documents) : 
```bash
pip3 install finalynx
cd somewhere/like/Documents  # ne pas aller dans les dossiers Homebrew ou autres fichiers internes
touch assistant_config.py  # <- coller le contenu de demo.py
python3 assistant_config.py
```

3. Installer via git, permet aussi de modifier le code : 
```bash
cd somewhere/like/Documents/  # ne pas aller dans les dossiers Homebrew ou autres fichiers internes
git clone https://github.com/MadeInPierre/finalynx.git
cd finalynx
pip3 install poetry && poetry check && poetry install
pip3 install -e .
python3 examples/demo.py
```

**Comment by Sigri44** [comment]
Oui c'est bien sur Mac, c'est un équivalent apt (: 

Ah non j'ai suivi la doc et pris que le .py ahah quel boulet, je retest ça, ça devrait effectivement être mieux ;)

Merci pour le tips poetry, je ne connaissais pas.

**Comment by Sigri44** [comment]
Beaucoup mieux, merci beaucoup ! Je suis pas expert Python, je pensais que le .py suffisait tant qu'on installait les dépendances. Tout est bon merci beaucoup, je vais pouvoir m'amuser avec ça !

Have fun

**Comment by MadeInPierre** [comment]
Génial, content que ce projet serve à d'autres ! Hésite pas à ouvrir discussions/issues si t'as des questions ou idées d'amélioration, avec plaisir ^^ 

Je suis en train de rédiger des tutoriels step-by-step, ça arrive quand j'ai le temps. Ca te donne le temps de construire ta config version simple avant de tenter les features plus sympa bientôt :wink: 

Have fun à toi, en espérant qu'il n'y ait pas de bugs :upside_down_face:
