### ISSUE TITLE
Question sur la partie Performance

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#123]
Hello
Je vois qu'il y a une partie Performance sur la console. J'ai rempli le champ perf de dossier ou ligne, mais cela ne change rien. Il y a toujours 0. Peut-on avoir plus de détail pour sa mise en place ? :)

**Comment by MadeInPierre** [comment]
Je vais créer des tutoriels/guides dans la semaine, il est temps que je m'y mette :sweat_smile: 

Pour patienter j'explique ici vite fait, tu peux déclarer des lignes avec une performance prévue : 

```python
from finalynx import LinePerf
Line(..., perf=LinePerf(3))  # 3% expected yearly performance
``` 

Si tu veux mettre la même performance pour plusieurs lignes dans un dossier d'un coup (et lignes dans les sous-dossiers), il y a un raccourci : 

```python
Folder(..., perf=LinePerf(3), children=[...])
```

Ensuite, Finalynx calcule deux performances affichées à côté des deltas : 
- **Current** prend les valeurs en temps réel de tes investissements et s'en sert pour calculer la moyenne de performance attendue de ton portefeuille entier
- **Planned** prend les valeurs idéales calculées à partir des `Target` définis un peu partout pour te dire quelle performance tu aurais si tous tes targets étaient exactement respectés.

Bien sûr, current = target si tu est déjà aligné avec tes targets :slightly_smiling_face:

**Comment by sebfar9172** [comment]
Mais en planned on devrait pas avoir la valeur cible. Là j'ai 8% partout et à la fin cela me dit planned à 5%

**Comment by MadeInPierre** [comment]
Si tu fais : 

```bash 
python your_config.py perf
```

Tu devrais voir la performance enregistrée pour chaque ligne et ensuite calculée pour chaque dossier, il y a peut-être une erreur de calcul. 

Après si tes CCP/Livrets sont à 3% c'est peut-être normal d'avoir un peu moins du coup ?

**Comment by sebfar9172** [comment]
Ok avec cette commande je vois ce qui ne va pas. Quand j'affecte une performance a un dossier cela ne descend pas au niveau des enfants

**Comment by sebfar9172** [comment]
En fait cela ne descend pas de 2 niveaux

**Comment by MadeInPierre** [comment]
Ah donc 1 niveau seulement (aka. seulement les `Line` directement dans le `Folder` mais pas celles dans les `Folder` descendants) ? Je regarde

**Comment by sebfar9172** [comment]
Pas de soucis j'ai contourné le pb et en effet c'est plus cohérent les projections

**Comment by MadeInPierre** [comment]
Cool, j'essaye quand même de résoudre car c'est moche du coup (et compliqué pour les débutants)
