### ISSUE TITLE
Décalage du tableau de recommandation avec les lignes en €

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#124]
![ecran4](https://github.com/MadeInPierre/finalynx/assets/52531214/f5e1bae2-3cb4-426a-a6af-aeabf7754bcc)

**Comment by sebfar9172** [comment]
Je pense que cela vient de la police de caractères

**Comment by MadeInPierre** [comment]
Houlà, malheureusement je ne peux rien faire pour ça ^^' il faut que tu installes une police avec les caractéristiques suivantes : 
- Supporte l'UTF-8
- Police de type **Monospace** (tous les caractères prennent le même espace horizontal, utile pour le code)

Ton terminal doit aussi supporter l'UTF-8 et les couleurs. Perso je suis sur linux avec `gnome-terminal` et la police `Monospace` par défaut sur Ubuntu.
