### ISSUE TITLE
Soucis sur le calcul de la tolérance

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#128]
Hello
Alors j'ai un investissement qui représente 1% et mon objectif est de 2%. Je souhaite qu'il y ait une tolérance de 1%
J'ai essayé plusieurs paramétrage mais sans que cela fonctionne.

target=TargetRatio(2, 0, 2) fonctionne mais si j'applique le même principe partout pour tous ceux où je suis déjà à l'objectif il m'indique que je suis dans la zone de tolérance alors que je devrais être à OK

target=TargetRatio(2, 1, 0), m'indique que c'est ok alors que je suis dans la zone de tolérance

bref entre la tolérance et la zone je ne comprends pas trop le principe

**Comment by sebfar9172** [comment]
J'ai besoin d'avoir le paramétrage pour qu'une ligne avec un targetratio 
soit à tolerated pour un écart de 1%
soit à Ok pour un écart de 0%

Je n'y arrive pas

**Comment by sebfar9172** [comment]
j'ai trouvé en mettant

target=TargetRatio(2, 0.5, 1)

**Comment by MadeInPierre** [comment]
Yes ça m'a l'air bien :slightly_smiling_face: voir la [définition de la classe](https://github.com/MadeInPierre/finalynx/blob/91ebcf25813fdb051c46a8c48a51bdc32720b359/finalynx/portfolio/targets.py#L261-L271) : 
- Target: pourcentage cible (2%)
- Zone: tolérance autour des 2% pour être considéré OK (vert), soit entre `target - zone` et `target + zone`
- Tolerance: tolérance autour de la zone pour être considéré TOLERATED (jaune), soit entre `target - zone - tolerance` et `target + zone + tolerance`

**Comment by sebfar9172** [comment]
Oui j'avais vu le code mais même en voyant les formules cela ne m'a pas complètement aidé 
Après je me suis dit c'est du float donc tu as sûrement arrondi ce qui est affiché

**Comment by MadeInPierre** [comment]
Oui c'était un peu illisible sinon mais du coup c'est moins pratique pour les petits pourcentages ^^' Juste pour vérifier que tu as ce que tu veux tu peux enlever le `round` [sur cette ligne](https://github.com/MadeInPierre/finalynx/blob/91ebcf25813fdb051c46a8c48a51bdc32720b359/finalynx/portfolio/targets.py#LL53C18-L53C18) si tu veux!
