### ISSUE TITLE
Recommandation : hiérarchie dans la partie Folder

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#131]
Hello
Serait il possible que dans la partie Dossier Recommandation, on affiche une arborescence avec le parent direct du dossier concerné ?

Par exemple j'ai fait des dossiers par plateforme de crowdfunding (avec chacun une enveloppe) en faisant un COLLAPSE pour ne pas avoir les lignes. Cela m'affiche les dossiers correspondant pour chaque plateforme où il y a un delta. J'aimerai que cela soit présenté comme un PEA

Crowdlending
- BienPreter -2500
- Wesharebonds +1500

**Comment by MadeInPierre** [comment]
Hello, je viens d'essayer ça donne ça : 

<img src="https://github.com/MadeInPierre/finalynx/assets/12670280/bb7a116e-7444-423b-982b-25fdac04da7f" width=400/>


C'est ce que tu cherches ? Quelque chose à améliorer ? J'ai l'impression que ça fait un peu lourd pour rien mais pas d'avis tranché...

**Comment by sebfar9172** [comment]
C'est tout à fait cela mais peut être pas dans le cas où il y a qu'une ligne

**Comment by MadeInPierre** [comment]
Maybe... comme ça ? :) ça vaut le coup de mettre les deltas devant les dossiers comme les envelopes ? 

<img src="https://github.com/MadeInPierre/finalynx/assets/12670280/98560eb1-36cf-4755-8bdf-2a38c85ce07b" width=400/>

**Comment by MadeInPierre** [comment]
Done, ça donne envie de trier les dossiers/envelopes par delta en ordre décroissant, je le ferai un autre jour :) Merci pour l'idée

![image](https://github.com/MadeInPierre/finalynx/assets/12670280/c0193a67-04d0-4d89-af5d-a7c5bd7ec790)

**Comment by sebfar9172** [comment]
Top merci
