### ISSUE TITLE
Erreur 10.2

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#132]
![image](https://github.com/MadeInPierre/finalynx/assets/52531214/b961cf01-b501-4a12-9d18-906726e495d1)

**Comment by sebfar9172** [comment]
et si je remplace attr par dataclasses

![image](https://github.com/MadeInPierre/finalynx/assets/52531214/c58bab99-f195-4524-9885-01d55adfac7b)

**Comment by MadeInPierre** [comment]
Ah mais pardon tu l'as déjà fait... :facepalm: j'ai pas d'erreur chez moi, tu as mis quoi comme config? Tu as essayé de mettre des nouveaux sidecars?

**Comment by sebfar9172** [comment]
Je n'ai rien changé. Tout fonctionnait dans la version précédente

**Comment by sebfar9172** [comment]
assistant = Assistant(portfolio, buckets, envelopes, ignore_orphans=True, hide_amounts=False, hide_root=False, active_sources=["finary", "realt"], sidecars=["[ideal],[delta]", "[delta]"], theme=MyTheme())
assistant.add_source(SourceRealT("0x...."))
assistant.run()

**Comment by MadeInPierre** [comment]
Pourrais-je avoir ta version Python ? 

```bash
python3 --version
```

**Comment by sebfar9172** [comment]
3.10

**Comment by MadeInPierre** [comment]
Ahhhh mes excuses ! Il y a eu un changement ! 2min je rédige

**Comment by MadeInPierre** [comment]
J'ai mis à jour la [**release**](https://github.com/MadeInPierre/finalynx/releases/tag/v1.20.2)
