### ISSUE TITLE
Problème génération d'image

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#133]
Bonjour
Que faut il comme package pour que cela fonctionne ? J'ai l'erreur chrome introuvable

**Comment by MadeInPierre** [comment]
Hello, je ne sais pas trop ^^'

J'ai juste essayé le paquet `html2img` sur pip pour convertir l'HTML généré par la console vers un PNG pour Telegram, et ça a marché chez moi. Juste pour être sûr, vérifies qu'il est bien là :

```
pip install html2img
```

Il faut que tu aies chrome installé (peut-être chromium aussi ?) pour que ce paquet fonctionne, si c'est toujours pas bon il faudrait voir avec eux sur leur repo GitHub ?

**Comment by sebfar9172** [comment]
J'ai avancé et j'ai une erreur 

Running as root without --no-sandbox is not supported

**Comment by MadeInPierre** [comment]
Hello, est-ce que tu pourrais essayer cette solution https://github.com/vgalin/html2image/issues/4#issuecomment-735014697 ? Je m'y connais autant que toi pour cette partie, j'espère que ça suffira... Il y a [quelques autres issues](https://github.com/vgalin/html2image/issues?q=Running+as+root+without+--no-sandbox+is+not+supported) qui parlent de la même erreur aussi

**Comment by MadeInPierre** [comment]
Salut ! J'espère que tu vas bien, juste pour info tu as pu t'en sortir pour ceci ? :slightly_smiling_face: Je peux fermer cette issue ?

**Comment by sebfar9172** [comment]
Oui, tu peux fermer
Salut
