### ISSUE TITLE
Bug perf

### ISSUE THREAD

**Issue by Kbou32** [MadeInPierre/finalynx#143]
Bonjour au concepteur :)
Tu as fais un travail remarquable, merci à toi de le partager ! 

Je rencontre un bug au niveau des perf du portefeuille.
Il semblerait que les perf que j'indique via LinePerf s'applique directement aux perfs current au lieu des perfs planned.

Merci d'avance pour ton aide 

<img width="302" alt="Capture d’écran 2023-09-14 à 22 10 07" src="https://github.com/MadeInPierre/finalynx/assets/144576339/087cafcc-3df5-44eb-bd90-09eddf14d48f">
<img width="971" alt="Capture d’écran 2023-09-14 à 22 36 27" src="https://github.com/MadeInPierre/finalynx/assets/144576339/0259a375-b9b9-4685-bcdd-1b1e7823a33e">
<img width="313" alt="Capture d’écran 2023-09-14 à 22 53 05" src="https://github.com/MadeInPierre/finalynx/assets/144576339/4a7b144b-54b3-4306-a5bf-fb4f291aafa0">

**Comment by MadeInPierre** [comment]
Hello @Kbou32 ! Merci à toi d'essayer ce projet, ça fait plaisir de voir que ça peut servir à d'autres :) 

Je tente de décrire le fonctionnement actuel des perfs : la performance "Current" se sert des `LinePerf` que tu as définies et des valeurs actuelles investies sur chacune des lignes (données qui viennent de Finary). Le plus simple est d'utiliser un exemple (fictif juste pour illustrer). Si on a un dossier `Actions` avec deux lignes :
- "USA" avec 2000€ investis aujourd'hui et un `TargetRatio` à 80% et performance attendue de 8%,
- "Europe" avec 1000€ investis  aujourd'hui et un `TargetRatio` à 20% et performance attendue de 6%,

Alors la performance "Current" est de (8% × 2000 + 6% × 1000) / (2000 + 1000) = 7.33% / an avec tes positions d'aujourd'hui.

La performance "Planned" imagine que tu fasses un arbitrage tout de suite pour suivre tous tes `TargetRatio` correctement et estime ta performance attendue selon ta stratégie globale. Ainsi, on aurait ici (8% × **2400** + 6% × **600**) / (2000 + 1000) = 7.6%

J'espère que c'est clair et que ça correspond à ce que tu imaginais ? Pour l'instant Finalynx ne gère pas du tout les plus-value latentes, à ajouter potentiellement mais je n'ai que deux mains ^^

Avec plaisir pour discuter de choses à améliorer/ajouter ou d'autres soucis à résoudre !

**Comment by Kbou32** [comment]
I got it ! Merci pour ton retour express :)
