### ISSUE TITLE
Impossible d'affecter une enveloppe

### ISSUE THREAD

**Issue by Kbou32** [MadeInPierre/finalynx#144]
Hello, 
j'ai crée plusieurs enveloppes AV et bank comme indiqué sur le tuto.
La plupart fonctionne parfaitement, d'autres non alors que j'applique exactement le meme mode opératoire.

J'ai vérifié plusieurs fois, je ne vois pas où est mon erreur.

Le souci se pose pour les poches "energies renouvelables", "boursorama", "credit agricole" et "fortuneo".
Le code "envelope=av_xx" est bien reconnu étant donnée que je vois bien le code à 3 lettres s'afficher prés du nom et les enveloppes apparaissent bien dans les recommendations.
Le hic c'est que les montants de ces poches passent à 0€. 
Dès que je supprime le code envelope, le montant  réapparait ..

J'ai besoin de tes lumières ! 
Merci !

<img width="629" alt="Capture d’écran 2023-09-14 à 23 17 13" src="https://github.com/MadeInPierre/finalynx/assets/144576339/a2a42e98-1c7d-49b5-860f-f48c1c1e832e">
<img width="1018" alt="Capture d’écran 2023-09-14 à 23 16 51" src="https://github.com/MadeInPierre/finalynx/assets/144576339/df8e0513-da7b-45d2-9b8d-bccabc669c78">
<img width="963" alt="Capture d’écran 2023-09-14 à 23 16 07" src="https://github.com/MadeInPierre/finalynx/assets/144576339/2fe90dcb-0d96-4a1c-a3f7-21981c033aa1">

**Comment by MadeInPierre** [comment]
Ce coup ci j'ai l'impression que ça pourrait être de ma faute ^^' je regarde demain ! 

P.S. Juste au cas où, si tu utilises VSCode, [cette extension (black)](https://dev.to/adamlombard/how-to-use-the-black-python-code-formatter-in-vscode-3lo0) est géniale pour automatiquement formatter joliment ta config python à chaque ctrl+s sans se perdre dans les indentations/etc ^^

**Comment by Kbou32** [comment]
black, excellent !

**Comment by Kbou32** [comment]
Black, excellent merci !

**Comment by MadeInPierre** [comment]
Salut, si tu mets l'option `ignore_orphans` à `False` dans ta config, est-ce que les lignes bourso/etc s'ajoutent en bas ? Si oui ça veut dire que Finalynx ne reconnaît pas ton combo d'identifiants (la `key` de l'enveloppe et la `key` de la ligne). Pourrais-tu me donner le résultat du bloc qui apparaît en plus lorsque du exécutes : 

```bash
python your_config.py -cd
```

Ces options affichent ce qui a été trouvé depuis Finalynx avec les ID de chaque ligne/compte. Ca nous permettrait de vérifier que tu as mis les bons ID
