### ISSUE TITLE
Difficulté ajout de salaire

### ISSUE THREAD

**Issue by Kbou32** [MadeInPierre/finalynx#145]
Hello, 

Je suis debutant complet en codage et autre pythonerie.
J'ai passé beaucoup de temps à éplucher les exemples et tuto pour bien comprendre comment utiliser Finalinx et l'adapter à mes besoins.

Je m'en sortais pas trop mal jusqu'a ce que j'arrive à la partie salaire et ajout d' évènement. 
Je n'arrive pas à ajouter le salaire
Je sens que je suis pas loin mais il doit me manquer 1 ou 2 infos.

Peux tu me dire ce que j'ai oublié ?

Encore merci pour ton aide précieuse ! 

<img width="751" alt="Capture d’écran 2023-09-14 à 23 41 07" src="https://github.com/MadeInPierre/finalynx/assets/144576339/bccbab9a-8923-4301-9a85-35f6b656d121">

<img width="1109" alt="Capture d’écran 2023-09-14 à 23 34 09" src="https://github.com/MadeInPierre/finalynx/assets/144576339/149d534c-7903-4f7f-bc7c-746c03d1ec4a">

**Comment by MadeInPierre** [comment]
Hello! Impressionnant d'être arrivé aussi loin pour un complet débutant !

Tout m'a l'air bon vu d'ici à un détail près que je ne vois pas : la simulation ajoute ton épargne mensuelle (5500 - 1400) tous les mois dans la ligne `livreta`. Mais pour voir un changement sur ton portefeuille, il faut que cette ligne `livreta` soit utilisée quelque part dans ton `portfolio`.

Je viens de mettre à jour les tutoriels, pourrais-tu vérifier que tu utilises la même structure que l'exemple fourni ici : 

https://github.com/MadeInPierre/finalynx/blob/main/examples/tutorials/3_simulation/1_basics.py

Notamment la ligne 64 où `livreta` est référencé dans le portefeuille. C'est la seule manière pour Finalynx de savoir où mettre l'épargne et faire changer les montants dans l'arbre.

**Comment by Kbou32** [comment]
Hello, 
C'est ici que je bloque, justement je ne sais pas comment l' intégrer dans le portfolio.

portfolio = Portfolio(children=[livreta])
Comment l'ajouter au code déjà en place ?

J'aimerai que ca aille directement dans le moyen terme : 
<img width="849" alt="Capture d’écran 2023-09-15 à 11 40 27" src="https://github.com/MadeInPierre/finalynx/assets/144576339/913c2f2b-67dc-43e1-b920-d162cd1c2fa7">
<img width="423" alt="Capture d’écran 2023-09-15 à 11 40 46" src="https://github.com/MadeInPierre/finalynx/assets/144576339/eb6b91e5-f5b4-4670-a7ae-c206dbdae350">


D'ailleurs, ca serait super pratique si tu pouvais diffuser un fichier config complet et fonctionnel avec les différentes possibilités de Finalynx. 
Un peu comme le fichier démo mais avec tout ce que finalynx sait faire ! 
Il suffirait au débutant de copier ce qui l' intéresse.

Merci !

**Comment by MadeInPierre** [comment]
Hey! J'avais hésité d'ajouter ma config perso dans les exemples puisque j'utilise forcément la plupart des features, mais allez pourquoi pas :wink: Voici un [exemple complet](https://github.com/MadeInPierre/finalynx/blob/main/examples/full_example.py) qui peut te servir d'inspiration ^^

J'ai aussi ajouté un [dernier tuto simulation](https://finalynx.readthedocs.io/en/latest/quickstart/tutorials.html) pour avoir une structure complète (qui je sais fonctionne bien), de sorte à ce que le simulateur mette ton épargne dans ton Livret A et qu'elle soit automatiquement investie selon tes objectifs.

J'espère que ce sera clair, n'hésite pas à me dire si ça va ou s'il faut ajouter/changer quelque chose !
