### ISSUE TITLE
Support for loans and credit_accounts

### ISSUE THREAD

**Issue by Varal7** [MadeInPierre/finalynx#58]
Those correspond to

`https://api.finary.com/users/me/views/loans`

and 

`https://api.finary.com/users/me/views/credit_accounts`

The latter is not yet supported by finary_api, cf https://github.com/lasconic/finary/pull/68

It was not super obvious what structure finary is using to represent the data.

**Comment by MadeInPierre** [comment]
This would be a perfect issue for a PR :smile: Thanks for your feedback!
