### ISSUE TITLE
Currency display for targets

### ISSUE THREAD

**Issue by Varal7** [MadeInPierre/finalynx#59]
Currently the `render` code for targets hardcodes `€`.

Could let the user define which currency to use (or acquire it directly from corresponding `Node`).

**Comment by MadeInPierre** [comment]
I replaced every '€' occurrence with either the node currency or a default currency symbol in a new file `finalynx/config.py`. 

Let me know if you have a better solution, I guess this might not be convenient for you if you set a different value and the modified file gets always marked by git :sweat_smile:
