### ISSUE TITLE
Enable disabling the "render_delta" for targets

### ISSUE THREAD

**Issue by Varal7** [MadeInPierre/finalynx#60]
It seems like Finalynx allows customizing which info to display the `--format` argument. However, even with the barebones `python demo.py --format "[name]"`, I can't seem to deactivate `render_delta` for targets.

My current solution is to do

```
class MyFolder(Folder):
    def _render_delta(self, *args, **kwargs):
        return ""
```

And then use MyFolder whenever.

Works ok enough I guess

**Comment by MadeInPierre** [comment]
The right column with deltas acts as an independent _sidecar_ (this was the only way I found to align all deltas vertically on the right). You can try disabling this right panel with:

```bash
python your_config.py --hide-deltas  # type --help for more ideas
```

In the future, I'd like use this right column to customize it further and show (create an output format option for this sidecar).

**Comment by Varal7** [comment]
Ok, sorry I didn't look hard enough.
