### ISSUE TITLE
Crowdlending section

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#71]
The crowdlending section is not retrieve

**Comment by MadeInPierre** [comment]
Super merci, tu peux t'inspirer des issues déjà terminées comme #58 et #42. N'hésite pas si tu veux des directions/aide, je veux bien aider comme je peux !

**Comment by sebfar9172** [comment]
Bon c'est un peu compliqué pour moi mais pour information tu peux faire des ajouts manuels dans la section crowdlending

**Comment by MadeInPierre** [comment]
Aucun souci ! Je tente d'ajouter cette catégorie dans les prochains jours :slightly_smiling_face: Si un jour tu as envie d'apprendre certains morceaux n'hésite pas à créer un sujet de discussion, avec plaisir pour échanger.

**Comment by sebfar9172** [comment]
Voici pour le crowdlending

        # Crowdlending
        node = start_step("Crowdlending", tree)
        for e in ff.get_holdings_accounts(session, "crowdlending")["result"]:
            self._register_fetchline(
                fetched_lines=fetched_lines,
                tree_node=node,
                name=e["name"],
                id=e["id"],
                account=e["name"],
                amount=e["display_balance"],
                currency=e["display_currency"]["symbol"],
            )

**Comment by sebfar9172** [comment]
bon en fait les comptes de crowdlending synchronisé ne sont pas tagué , donc pour tout avoir j'ai fait

 # Crowdlending
    node = start_step("Crowdlending", tree)
    for e in ff.get_holdings_accounts(session)["result"]:
        self._register_fetchline(
            fetched_lines=fetched_lines,
            tree_node=node,
            name=e["name"],
            id=e["id"],
            account=e["name"],
            amount=e["display_balance"],
            currency=e["display_currency"]["symbol"],
        )

**Comment by sebfar9172** [comment]
Pourrais-tu ajouter une section crowdlending dans la partie exotique pour permettre de l'avoir dans le graphe ?

**Comment by sebfar9172** [comment]
J'ai ajouté dans le fichier constant pour la section exotique 

    CROWDLENDING = "Crowdlending"

**Comment by lasconic** [comment]
Je déplace la discussion ici.

Tu dois pouvoir mettre à jour le submodule git avec : 

```
git submodule update --remote --merge
```

**Comment by sebfar9172** [comment]
donc avec la dernière version de finary_api

        # Crowdlendings
        node = start_step("Crowdlendings", tree)
        for account in ff.get_portfolio_crowdlendings(session)["result"]["accounts"]:
            node_account = node.add(f"[bold]Account: {account['name']}")
            for e in account["crowdlendings"]:
                self._register_fetchline(
                    fetched_lines=fetched_lines,
                    tree_node=node_account,
                    name=e["name"],
                    id=e["id"],
                    account=account["name"],
                    amount=e["display_current_value"],
                    currency=e["currency"]["symbol"],
                )
