### ISSUE TITLE
Utilisation de la clé d'une ligne ne fonctionne pas

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#72]
J'ai plusieurs lignes d'une même action dans plusieurs supports. J'ai compris qu'il fallait utiliser la clé pour les distinguer mais cela fonctionne pas. Si je met le libellé j'ai la somme de toutes les lignes et si je met la clé cela ne me remonte rien. 

Line( "toto", key="24554")

**Comment by MadeInPierre** [comment]
C'est un souci que j'ai aussi découvert après-coup dans #47, je tente de résoudre ça ASAP ! J'avais trouvé le problème pour le cas des SCPI, tu as le problème sur un autre type d'actif ? Pourrais-tu donner quelques détails pour que je puisse chercher le problème ailleurs que les SCPI ?

**Comment by sebfar9172** [comment]
Ce sont des actions. Que veux-tu comme détail ?

**Comment by MadeInPierre** [comment]
Mince, le problème des SCPI ne s'applique visiblement pas aux actions, il faut trouver autre chose...

As-tu installé le projet via `pip install finalynx` ou `git clone` ? Si c'est le deuxième cas je veux bien te demander une info, sinon je tente de me débrouiller d'abord :) 

Les enveloppes qui contiennent la même action sont de quels types ? PEA et CTO ou autre ? Et l'action en question est un titre vif ou ETF ? Merci

**Comment by MadeInPierre** [comment]
Résolu, tu peux spécifier l'enveloppe de chaque ligne et le filtre devrait pouvoir différencier chaque occurence, let me know si c'est bon :crossed_fingers:

**Comment by sebfar9172** [comment]
Hello
Peux tu me donner un exemple d'implémentation de l'enveloppe au niveau d'un dossier

**Comment by MadeInPierre** [comment]
Hello, voici un exemple minimal : 

```python
# Début de ta configuration
if __name__ == "__main__":

    # Déclarer tes envelopes 
    av_linxea = AV("Mon AV", "AV ", date_created=date(2022, 7, 1), key="finary_account_name1")
    pea = PEA("Mon PEA", "PEA", date_created=date(2021, 7, 1), key="finary_account_name2")

    # Déclarer ta structure de portefeuille
    portfolio = Portfolio(..., children=[
        Line(..., key="finary_id1", envelope=av_linxea),
        Line(..., key="finary_id1", envelope=pea),
    ])
```

ainsi, chaque ligne aura deux enveloppes différentes et le même ID, ce qui devrait pouvoir les différentier si j'ai bien codé la chose...

S'il y a de l'intérêt pour ce projet je pourrai passerai un moment à rédiger des tutoriels pour bien démarrer :slightly_smiling_face: j'espère que c'est clair, n'hésite pas s'il y a besoin de plus de précisions.

**Comment by sebfar9172** [comment]
Merci je vais tester cela rapidement.. AV ou PEA ce sont des mots clés ou je mets ce que je veux ?

**Comment by MadeInPierre** [comment]
Les enveloppes sont toutes du type `Envelope`, après j'ai juste créé quelques variantes (e.g. PEA et AV) histoire de faire un petit raccourci au moment de définir l'enveloppe. En effet, quand on crée une `Envelope` on peut donner les dates de création/débloquage/fin d'imposition (qui servent dans le web dashboard), mais j'ai créé la sous-classe PEA qui ajoute automatiquement 5 ans à la date de création pour avoir la date de débloquage (plus pratique).

Voici la liste des envelopes dispo : https://github.com/MadeInPierre/finalynx/blob/main/finalynx/portfolio/envelope.py

Si ton type d'enveloppe n'est pas dans la liste des "raccourcis", tu peux utiliser la classe Enveloppe directement, exemple :

```python
cto_trading212 = Envelope("Mon CTO", "CTO", date_created=date(2020, 1, 1), ..., key="name_in_finary")
```

Les infos entre guillemets sont libres, c'est juste pour l'affichage ou pour renseigner le nom déclaré dans Finary.

**Comment by MadeInPierre** [comment]
Je viens d'ajouter [quelques explications ici](https://finalynx.readthedocs.io/en/latest/apidocs/finalynx/finalynx.portfolio.envelope.html#finalynx.portfolio.envelope.Envelope ) en espérant que ça aide !

**Comment by sebfar9172** [comment]
J'utilise le niveau dossier. Cela fonctionne très bien. Il y a une astuce si dans Finary, toutes mes assurances vie, s'appelle Assurance vie ?

**Comment by MadeInPierre** [comment]
Ah, j'espère que tu peux renommer tes AVs dans Finary car sinon je commence à être à court d'idées :sweat_smile:
