### ISSUE TITLE
Fetching issue

### ISSUE THREAD

**Issue by yovanoc** [MadeInPierre/finalynx#73]
I don't know since when this error happen but I can't fetch cryptos (I think) anymore

![image](https://user-images.githubusercontent.com/7302317/237031514-11b63bb8-2303-45aa-bbbf-366058931861.png)

**Comment by MadeInPierre** [comment]
Hey, j'ai dû faire pas mal de changements hier sur la partie fetch (dont sur la partie crypto alors que je n'en ai pas pour vérifier que tout est bon... :sweat_smile: )

Ce problème ressemble à https://github.com/MadeInPierre/finalynx/discussions/63#discussioncomment-5768053, pourrais-tu voir si tu as également des cryptos "fantôme" dans la réponse de l'API ? Il faudrait voir si le problème est le même ou une nouveauté à régler

**Comment by MadeInPierre** [comment]
Finary a bloqué l'API. 

```
{'result': None, 'message': 'Unauthorized', 'error': {'code': 'REQUEST_UNAUTHORIZED'}}
```

**Comment by MadeInPierre** [comment]
Je viens d'ajouter 1 BTC manuellement et ça marche, c'est donc une situation que je ne peux pas contrôler. Il me faut la réponse de l'API pour ton cas

**Comment by yovanoc** [comment]
En effet c'est le meme soucis que l'autre issue, j'ai une crypto fantôme, seulement ça ne passe pas par ton if dans _register_fetchline je sais pas pourquoi

**Comment by yovanoc** [comment]
Oh!

J'ai juste changé ta condition de:

```python
if not (name or id or account):
```

vers

```python
if not name or not id or not account:
```

et ça marche !
