### ISSUE TITLE
Enveloppe avec balancing

### ISSUE THREAD

**Issue by yovanoc** [MadeInPierre/finalynx#74]
FEATURE REQUEST

A moins que je me trompe il n'y a pas moyen de définir des target a l'intérieur meme des enveloppes. 
J'aimerais pouvoir à la fois utiliser target et perf.

**Comment by MadeInPierre** [comment]
Idée intéressante, à quoi cela te servirait ? Si une enveloppe correspond à un objectif, pourquoi ne pas l'associer à un Folder dans l'arbre et y associer les target/perf ?

**Comment by yovanoc** [comment]
En fait j'ai peut être mal compris les enveloppes si ça se trouve mais ma compréhension est la suivante:

j'ai mon PEA donc je créer une enveloppe PEA, dedans j'ai des actions avec différentes allocations, je souhaiterais donc dans l'arbre pouvoir mettre une perf si mon PEA mais à la fois pouvoir choisir les target des actions individuelles dedans.

J'espère avoir été clair

**Comment by MadeInPierre** [comment]
Je crois qu'on a juste une petite différence de vocabulaire (je choisir mal mes noms de classes ^^), voici ma méthode : 

Je déclare une structure de `Folder`/`Line`/`SharedFolder` indépendamment de mes enveloppes, ce qui est le coeur de l'utilité de ce projet (même si un Folder pourrait très bien être totalement dédié à des lignes contenues dans une seule enveloppe).

Ensuite, juste pour faire des jolis affichages et recommendations dans le futur, je déclare des `Envelope` (qui ne contiennent aucune ligne), elles représentent juste chaque enveloppe et stockent des infos telles que la date d'ouverture, déblocage, baisse de la fiscalité, etc. Ensuite, j'associe chaque `Line` avec son enveloppe associée, ce qui me permettra ensuite de faire des affichages classés par enveloppe en plus de l'arbre de base : 

![image](https://github.com/MadeInPierre/finalynx/assets/12670280/deb4da9d-6c63-4279-953c-a43b0a0dd293)

Un exemple d'utilisation ici : https://github.com/MadeInPierre/finalynx/issues/72#issuecomment-1539946680

J'espère que je suis clair aussi ? Est-ce qu'ajouter des target/perf aux enveloppes serait utile dans ce cas ?

**Comment by MadeInPierre** [comment]
Et on peut donc avoir un objectif par ligne en fonction de notre allocation globale, peu importe l'enveloppe choisie pour chaque investissement :slightly_smiling_face: 

![image](https://github.com/MadeInPierre/finalynx/assets/12670280/3b1ad848-89a4-4256-b6bf-c7e406488cf8)

**Comment by yovanoc** [comment]
Ok trés clair j'ai compris maintenant ! 

J'avais pas pigé car mes folder sont trés similaire à mes enveloppes en fait, du coup j'avais mal cerné la nuance

merci pour les précisions

**Comment by MadeInPierre** [comment]
Super, avec plaisir ! 

Maintenant avec Finalynx tu peux investir dans ton CTO et PEA en même temps en optimisant les frais/impôts pour chaque ligne sans avoir peur de te perdre dans la gestion, nouvelle phrase d'accroche :smile:
