### ISSUE TITLE
Crypto a 0€ qui s'affichent

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#78]
Hello
Dans la partie crypto, il y en a pas mal à zéro euros. Il faudrait ne pas les afficher.

**Comment by MadeInPierre** [comment]
Je ne suis pas sûr de comprendre le souci, j'aurais besoin d'une capture d'écran du problème car je n'ai pas de cryptos

**Comment by sebfar9172** [comment]
![image](https://github.com/MadeInPierre/finalynx/assets/52531214/492ceb5c-0963-4258-bc09-ce78d3f8ff1e)

**Comment by MadeInPierre** [comment]
A priori c'est résolu [avec ceci](https://github.com/MadeInPierre/finalynx/commit/05adaa1650b77965553ab387ab5c1ca7eca1c18c), pourrais-tu mettre à jour Finalynx : 

```bash
pip install finalynx --upgrade
```

Et me dire si c'est résolu ? :slightly_smiling_face:
