### ISSUE TITLE
Pea locked au lieu de taxed

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#81]
Hello
Je ne comprends pas, ce qui est fait pour le PEA. C'est indiqué qu'il est Lock pendant cinq ans. Ce n'est pas le cas, ça serait plutôt taxed.

**Comment by MadeInPierre** [comment]
Hello !

Pour moi le PEA est bloqué pendant 5 ans dans le sens où il est automatiquement fermé si on fait un retrait avant les 5 ans, donc je l'ai mis en bloqué. 

Tu verrais les choses autrement ? Peut-être faudrait-il créer un nouveau statut genre Held (retenu en français) ?

Si tu préfères le déclarer en Taxé, tu peux utiliser cette ligne à la place :

```python
# Déclarer manuellement un PEA
pea = Envelope("Mon PEA", "PEA", date_created(2023, 1, 1), date_untax=date(2028, 1, 1))
```

**Comment by sebfar9172** [comment]
Non tu peux clore
