### ISSUE TITLE
Include/exclude lines when using Folder autofill

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#82]
L'extraction issue de Finary identifie bien les fonds euros. Est il possible quand on laisse les lignes d'une assurance vie se générer seules de ne pas avoir les fonds euros ?

En gros je veux séparer les fonds euros sans avoir à saisir chaque ligne de mon assurance vie pour ne pas mettre les fonds euros

**Comment by MadeInPierre** [comment]
Alors là je t'avoue que ça commence à être compliqué, techniquement tout est possible mais je pense que tu mettras moins de temps à ajouter les lignes que moi pour l'implémenter 😅 Je ne bosse pas à temps plein sur ce projet :P 

Je garde l'idée ouverte au cas où je trouve une idée/compromis un jour :slightly_smiling_face:

**Comment by sebfar9172** [comment]
En fait la nuit ma portée conseil lol
En fait je peux garder comme cela car cela me permet de voir exactement ce que j'ai sur une assurance vie et de l'autre avoir une vue par fond euros

**Comment by MadeInPierre** [comment]
Ah tu as créé plusieurs vues ? Par curiosité, comment as-tu fait ? :)

**Comment by sebfar9172** [comment]
Je n'ai pas pu à cause du problème sur Netessima

**Comment by MadeInPierre** [comment]
En effet j'ai l'impression qu'on touche la limite de l'automatisation, sinon il faudrait devenir comme finary et classifier toutes les lignes automatiquement, je n'ai pas ces ressources :) 

Vu que le fait d'auto-remplir le dossier ne permet pas de spécifier quelle ligne est de quel type, je me dis que permettre de personnaliser cette fonction n'a pas beaucoup de sens. Je me permets donc de fermer cette issue, n'hésite pas à la réouvrir si tu as un "use case" utile qui aurait besoin de cette feature.
