### ISSUE TITLE
Line 'Netissima' matched with multiple nodes, updating first only.

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#83]
Bonjour

j'ai un soucis pour afficher mes fonds euros : Netissima

J'ai la warning Line 'Netissima' matched with multiple nodes, updating first only.

Voilà ce que la récupération de Finary donne : 

![image](https://github.com/MadeInPierre/finalynx/assets/52531214/0fe282ea-88b8-47f2-b1c4-352fb01e74fb)

Que dois je faire ?

J'ai essayer cela plusieurs choses mais rien ne fonctionne : 

                        children=[
                            Line("Netissima", key="179669" ),
                            Line("Netissima", key="179662" ),
                            Line("Netissima", key="179666" ),
                        ]

**Comment by sebfar9172** [comment]
J'ai identifié le soucis 
Mon fond euro est dans mon assurance vie que j'ai paramétrer pour générer automatiquement toutes les lignes.
Et quand j'essaye de faire une lignes spécifiques pour ce fonds euros, cela pose problème.
Pour régler problème, je suis obligé de faire les lignes de mon assurance vie une par une, sans y mettre le fond euros.

**Comment by MadeInPierre** [comment]
Ah oui, finalynx cherche la première ligne qui match (même clé/enveloppe), remplit 

J'espère que ce n'est pas trop un souci ? Je m'occuperai de #82 si je trouve une idée, mais pour l'instant je dirais que les lignes des AV ne changent pas si souvent que ça pour un stratégie long terme ^^

**Comment by sebfar9172** [comment]
Non, au lieu de remplir en automatique, j'ai ajouté ligne par ligne, ce qui m'a permis aussi de distinguer eTF, action obligation

**Comment by MadeInPierre** [comment]
Ca marche, un peu manuel en effet mais c'est quand même sympa une fois que c'est terminé :grin: Je ferme cette issue du coup.
