### ISSUE TITLE
Mise à jour impossible

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#95]
Bonjour
Je suis en 1.14.4. J'utilise la commande pip et cela ne me fait pas de mise à jour. Je n'ai pas d'erreur. Les lignes défilent mais à la fin je n'ai pas changé de version.

**Comment by MadeInPierre** [comment]
Bonjour,

As-tu bien utilisé l'option `--upgrade` ? Aussi, j'ai cru voir dans d'autres issues que tu as modifié le code de Finalynx, peut-être faut-il les enlever ? Le plus simple est de désinstaller Finalynx : 

```bash
pip install --upgrade --force-reinstall finalynx
```

D'ailleurs, rien à voir mais je veux bien ton mail utilisé pour ton compte GitHub pour te déclarer en auteur des ajouts crowdlending/startup ^^

**Comment by sebfar9172** [comment]
Hello comment puis je te transmettre mon email sans que cela soit vu de tout le monde ?
J'attendrais que tu déploie mes modifications pour tout réinstaller car je ne veux pas perdre ce que j'ai fait :)

**Comment by MadeInPierre** [comment]
Si tu vas dans ton compte GitHub > Paramètres > Emails, tu devrais voir une addresse qui ressemble à `ID+username@noreply.user.github.com`, celle-ci n'a rien de confidentiel et te permet de te déclarer comme auteur ^^

**Comment by sebfar9172** [comment]
2531214+sebfar9172@users.noreply.github.com

**Comment by MadeInPierre** [comment]
Alors là j'ai rien compris :joy: :sweat_smile: 

Je viens de push et GitHub a dit que l'auteur est un certain **kevin92805**, il sort d'où ???

Je vois si je peux changer ça... en tout cas tes features sont dispo, merci et bravo !

**Comment by sebfar9172** [comment]
J'avais ajouté des constantes, si tu peux les ajouter ? 

AssetClass.EXOTIC                                         
AssetSubclass.CROWDLENDING

**Comment by sebfar9172** [comment]
Au final c'est que malgré tout je suis toujours en version 14.4

**Comment by sebfar9172** [comment]
J'ai tout supprimé et quand je fais une installation propre 

pip install finalynx

Cela m'installe 14.4

**Comment by MadeInPierre** [comment]
Bizarre, la nouvelle version 1.15 est bien dispo sur pip : https://pypi.org/project/finalynx/

Peut-être bien désinstaller d'abord : 

```bash
pip uninstall finalynx
pip install finalynx
```

**Comment by MadeInPierre** [comment]
Ah, c'est peut-être que Finalynx a maintenant besoin de python 3.10 (au lieu de 3.8 avant) car j'ai récemment utilisé le nouveau `finary_uapi`, voir #92 et https://github.com/MadeInPierre/finalynx/pull/85#issuecomment-1557069463, qui demande 3.10

Si tu lances juste la commande `python --version` dans le terminal, tu as quelle version ? Il faut peut-être passer à 3.10...

**Comment by sebfar9172** [comment]
J'ai désinstallé Linux et réinstaller (je suis sous window). 
Je récupère toujours la 14.4
Je suis en Python 3.9

**Comment by MadeInPierre** [comment]
Malheureusement pour toi, il faut Python 3.10 :sweat_smile: désolé, mais je crois que pip refuse d'installer le "nouveau" finalynx vu qu'il demande 3.10

J'espère que passer à 3.10 n'est pas trop lourd :pray:

**Comment by MadeInPierre** [comment]
Si c'est trop compliqué, on peut demander à l'auteur de finary_api pour voir s'il peut baisser sa dépendance à python 3.8.

Je ne pense pas pouvoir trop t'aider pour windows, je suis sur full linux ^^'

**Comment by sebfar9172** [comment]
J'ai finalement installé une autre distribution et c'est bon

**Comment by MadeInPierre** [comment]
Génial :grin:

**Comment by MadeInPierre** [comment]
@sebfar9172 J'ai contacté le support GitHub et ils ont trouvé comment résoudre le souci d'auteur ! Te voilà contributeur à ton juste titre ^^
