### ISSUE TITLE
erreur sur date unlock

### ISSUE THREAD

**Issue by sebfar9172** [MadeInPierre/finalynx#98]
Hello

J'ai cette enveloppe : 

```python
startupNothing=Envelope("Nothing", "STP", date_created=date(2022, 4, 6), date_unlock=date(2027, 4, 6))
```

cela me fait une erreur en m'indiquant que la date de création doit être inférieure à la date unlock mais c'est bien le cas car 2022 < 2027

je pense que c'est la règle suivante qui pose problème, en effet si on ne saisit pas de date_untax cela met date_created donc on a 
 date_created < date_unlock < date_created ce qui ne fonctionne pas :)

```python
self.date_created = date_created
self.date_unlock = date_unlock if date_unlock else date_created
self.date_untax = date_untax if date_untax else date_created
 
if not (self.date_created <= self.date_unlock <= self.date_untax):
    raise ValueError("Envelope dates must be ordered by created <= unlock <= untax")
```

**Comment by MadeInPierre** [comment]
Ah mince bien vu ! Le fix suivant est très simple et me semble correct : 

```python
self.date_untax = date_untax if date_untax else self.date_unlock
```

Ca te paraît bon ? Fi nde journée, cerveau fatigué x)

**Comment by sebfar9172** [comment]
En effet c'est le plus simple (Pour l'instant j'ai ajouté la date untax )

**Comment by sebfar9172** [comment]
> Ca marche je push de suite, si un jour ça te tente d'upload les contributions toi-même n'hésite pas, avec plaisir pour expliquer ^^

Yes cela sera plus simple

**Comment by MadeInPierre** [comment]
Au prochain bug que tu trouves si t'es chaud on se fera les étapes ensemble :grin: merci pour celui-ci !
